---
name: run-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  
jobs:
  orchestrate-minor-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '.0')
    strategy:
      fail-fast: false
      matrix:
        project: [apm-server, observability-dev, observability-docs]
    steps:
      - run: |-
          gh workflow run \
            run-minor-release \
            --field "version=${GITHUB_REF#refs/*/}" \
            --repo "${REPO}" 
        env:
          REPO: 'elastic-release-automation/${{ matrix.project }}'

  orchestrate-patch-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '.0')
    strategy:
      fail-fast: false
      matrix:
        project: [apm-server]
    steps:
      - run: |-
          gh workflow run \
            run-patch-release \
            --field "version=${GITHUB_REF#refs/*/}" \
            --repo "${REPO}" 
        env:
          REPO: 'elastic-release-automation/${{ matrix.project }}'
