---
name: run-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

# Avoid concurrency so we can watch the releases correctly
concurrency:
  group: ${{ github.workflow }}
  
jobs:
  orchestrate-minor-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '.0')
    strategy:
      fail-fast: false
      matrix:
        project: [apm-server, observability-dev, observability-docs]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/run
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          project: ${{ matrix.project }}
          release-type: 'minor'

  orchestrate-patch-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '.0')
    strategy:
      fail-fast: false
      matrix:
        project: [apm-server]
    steps:
      - uses: actions/checkout@v4
      - run: echo '### minor - ${GITHUB_REF#refs/*/}' >> $GITHUB_STEP_SUMMARY
      - uses: ./.github/workflows/run
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          project: ${{ matrix.project }}
          release-type: 'patch'
