---
name: run-minor-release

on:
  # Alternative 1
  workflow_dispatch:
    inputs:
      version:
        description: 'The version (semver format: major.minor.patch)'
        required: true
        type: string
  # Alternative 2
  push:
    tags:
      - 'patch-[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

# Avoid concurrency so we can watch the releases correctly
concurrency:
  group: ${{ github.workflow }}

jobs:
  # Alternative 1
  run-patch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo '### patch - ${{ inputs.version }}' >> $GITHUB_STEP_SUMMARY
      - run: echo 'add your code'

  # Alternative 2
  run-patch-tag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup release version
        run: |-
          VERSION=${GITHUB_REF#refs/*/patch-}
          echo "### patch - ${VERSION}" >> $GITHUB_STEP_SUMMARY
      - run: echo "add your code for ${VERSION}"
