---
name: run-minor-release

on:
  # Alternative 1
  workflow_dispatch:
    inputs:
      version:
        description: 'The version (semver format: major.minor.patch)'
        required: true
        type: string
  # Alternative 2
  push:
    tags:
      - 'minor-[0-9]+.[0-9]+.0'

permissions:
  contents: read

# Avoid concurrency so we can watch the releases correctly
concurrency:
  group: ${{ github.workflow }}

jobs:
  # Alternative 1
  run-minor-dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - run: echo '### minor - ${{ inputs.version }}' >> $GITHUB_STEP_SUMMARY
      - run: echo 'add your code'

  # Alternative 2
  run-minor-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: setup release version
        run: |-
          VERSION=${GITHUB_REF#refs/*/minor-}
          echo "VERSION=${VERSION}"     >> $GITHUB_ENV
          echo "### minor - ${VERSION}" >> $GITHUB_STEP_SUMMARY
      - run: echo "add your code for ${VERSION}"
